version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    container_name: doulingo_pg
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-doulingo}
      PGDATA: /data/postgres
    volumes:
      - ./pgdata:/data/postgres
    restart: unless-stopped

volumes:
  postgres:
